# Generated by Django 5.2.8 on 2025-11-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inscription', models.IntegerField()),
                ('id_matiere', models.IntegerField()),
                ('id_enseignant', models.IntegerField()),
                ('sequence1', models.FloatField(blank=True, null=True)),
                ('sequence2', models.FloatField(blank=True, null=True)),
                ('sequence3', models.FloatField(blank=True, null=True)),
                ('sequence4', models.FloatField(blank=True, null=True)),
                ('sequence5', models.FloatField(blank=True, null=True)),
                ('sequence6', models.FloatField(blank=True, null=True)),
                ('trimestre1', models.FloatField(blank=True, null=True)),
                ('trimestre2', models.FloatField(blank=True, null=True)),
                ('trimestre3', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('id_inscription', 'id_matiere')},
            },
        ),
    ]
