# Generated by Django 5.2.8 on 2025-11-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='trimestre1',
        ),
        migrations.RemoveField(
            model_name='note',
            name='trimestre2',
        ),
        migrations.RemoveField(
            model_name='note',
            name='trimestre3',
        ),
    ]
