# Generated by Django 5.2.8 on 2025-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='classe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
