# Generated by Django 5.2.8 on 2025-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_bulletin_classe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
