# Generated by Django 5.2.8 on 2025-11-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_bulletin_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='trimestre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
