# Generated by Django 5.2.8 on 2025-11-18 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0004_alter_bulletin_trimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
