# Generated by Django 5.2.8 on 2025-11-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0005_bulletin_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebulletin',
            name='sequences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
