# Dockerfile (dans Systeme_Authentification/)
FROM python:3.10.12

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["sh", "-c", "python manage.py runserver 0.0.0.0:8000 & python manage.py runconsumer"]